### ISSUE TITLE
Datasearch styling: z-index in .rbc-datasearch is set to 100

### ISSUE THREAD

**Issue by devAbnull** [appbaseio/reactivebase#115]
The css for datasearch as shown below has `z-index=100` that causes issues while working with popup overlays.
```css
.rbc.rbc-datasearch {
    margin-top: 10px;
    padding: 0;
    z-index: 100;
}
````
